### ISSUE TITLE
[Homework 2] 小仔整理書架

### ISSUE THREAD

**Issue by troublecat55** [coding-coworking-club/advanced-python-fall-2021#14]
## 提交連結
還沒提交

## 問題描述
不好意思我研究了一陣子，實在看不懂題目，例如：
hint: sample 1
\asd\qwe/rt/ ->\asdewqrt/ ->trqwedsa
\asdewqrt/是經由什麼轉換順序變成trqwedsa的？

先謝謝助教，辛苦了！

**Comment by St-Ren** [comment]
\asd\qwe/rt/ -> \asd ( qwe -> ewq) rt/ ->\asdewqrt/   ->trqwedsa

**Comment by troublecat55** [comment]
解出來了感謝~
