### ISSUE TITLE
[Homework 3] 小仔坐飛機

### ISSUE THREAD

**Issue by ssss4481** [coding-coworking-club/advanced-python-fall-2021#22]
## 程式碼

```python

```

## 問題描述

1.起始點s與目的地d
是否保證: s < d?
若有s == d(原地)或s > d(不可能抵達) 的情形，
因為無法從票價計算出答案，
我應該給出甚麼答案?

2.票價
是否保證:票價>=0 ?
雖然說依照題目的情境來說票價應該不可能為負，
但若是測資實際上有負的那我可能要考慮別的作法。

以上兩個問題，不好意思麻煩各位了。

**Comment by St-Ren** [comment]
1. 票價是雙向的所以都能抵達，如果在原地就不需要花費票價移動囉
2. 飛機公司應該是不會倒貼錢的XD 會有無限循環的。

**Comment by ssss4481** [comment]
原來是雙向 
我一直以為是單向XD
感謝回覆
