### ISSUE TITLE
[Homework 3] 交朋友

### ISSUE THREAD

**Issue by alemapnil** [coding-coworking-club/advanced-python-fall-2021#31]
## 程式碼

```python

4 3 1 2 3 9 1 2 >>17
o x x o x o x o

5 4 3 1 2 3 9 1 2 >>21
o x o x o x o x o


```

## 問題描述

可否請助教給點思路，這題應該要怎麼切入才對。sample 2的情況是取4,2,9,2，先取9，往左左、往右右各別取2，在左邊情況，因為4比3大，所以取4，但若4的左邊還有5，此情況就要取5。但要怎麼在符合題目的條件下取得最大值呢

**Comment by St-Ren** [comment]
https://github.com/coding-coworking-club/advanced-python-fall-2021/issues/27#issue-1042011424
