### ISSUE TITLE
[Homework 1] 歡樂智多金

### ISSUE THREAD

**Issue by alemapnil** [coding-coworking-club/advanced-python-fall-2021#7]
## 提交連結

https://judge.ccclub.io/status/7079d0d601cf3a34e3b3f50e877a40b3

## 程式碼

```python
input_list=sorted([i for i in input().split(',')],reverse=True)
ans=int(''.join(input_list))
print(ans)
```

## 問題描述

我知道用我的程式碼會WA，原因是如果input是76,762 or 16,162,164 or 1,109 這三種情況會無法印出最大值。我花了很多時間，始終想不到要怎麼處理這些情況，例如5,52  or 5,56就會不同排序，5,52,56的排序又會不同，一直想不到規律。可否請助教提供方向，謝謝

**Comment by yichensu** [comment]
@alemapnil 
以粗略的方向來說，會建議你可以想想看不同位數兩兩比較的時候，你腦中的邏輯是怎麼運行，再嘗試去撰寫出來。
